<template>
<el-dialog title="Select Fields to Display" :visible="true">

  <el-form
    v-model="dialogForm"
  >
    <div style="text-align:center;">
    <table style="width:75%">
      <col width="50">
      <col width="*">
      <col width="*">

      <tr>
        <th>&nbsp;</th>
        <th>Field Name</th>
        <th>Type</th>
      </tr>

      <tr
        v-for="fieldname in recordKeys"
        :key="fieldname"
      >
        <td>
          <i v-if="dialogForm[fieldname]==''" class="el-icon-minus" />
          <i v-else class="el-icon-circle-check" />
        </td>

        <td>{{fieldname}}</td>

        <td>
          <el-select placeholder="Select a type"
            v-model="dialogForm[fieldname]"
          >
          <el-option label="Not Selected" value="" />
          <el-option
            v-for="item in propertyTypes"
            :key="item.value"
            :label="item.label"
            :value="item.value"
          />
          </el-select>
        </td>
      </tr>
    </table>
    </div>
  </el-form>

  <span slot="footer" class="dialog-footer">
    <el-button
      @click="handleCancelDialog"
    >
      Cancel
    </el-button>
    <el-button type="primary"
      @click="handleConfirmDialog"
    >
      Save
    </el-button>
  </span>
</el-dialog>
</template>

<script lang="ts">
/*
  Select Service Fields Dialog

  requires a Service Watcher and an example JSON record
  Listens to Feathers Service for dialog requests

  returns a record, property names maps to types
  {
    text: "number",
    _id: "string"
  }
*/
// Libs
import Vue from 'vue'

// Constants / Interfaces
import { PropertyTypes } from '@/app-constants'
import { IServiceConnection, DataRecord } from '@/interfaces'

// Components
import FGuiCtrl from '@/controllers/feathers-gui-ctrl'
import { sanitizeRecordFields } from '@/utils/data-utils'

export default Vue.extend({

  props: ['data', 'cancel', 'success'],

  data() {
    return {
      dialogForm: {}, // generated by watchers
      propertyTypes: PropertyTypes,
    }
  },

  computed: {

    recordKeys() : string[] {
      return Object.keys(this.dialogForm)
    },

    /*
      get fields from Selected Service
      unpack structure into key/value format
    */
    cleanedServiceFields() {
      const { serviceConnection } = this
      let fields = serviceConnection.fields
      const clean:DataRecord = {}
      fields.forEach(function(field) {
        const { property, type } = field
        clean[property] = type || ''
      })
      return clean
    },

    dataRecord() : DataRecord {
      const { record } = this.data
      return record
    },

    serviceId() : string {
      return this.data.serviceId
    },

    serviceConnection() : IServiceConnection {
      const { serviceConnection } = this.data
      return serviceConnection as IServiceConnection
    },

  },

  methods: {

    handleCancelDialog() {
      const { cancel } = this
      if (cancel) cancel()
    },

    /*
      take results of Dialog Form and filter out ""
    */
    handleConfirmDialog() {
      const { success } = this

      const dialogForm:DataRecord = this.dialogForm
      const fields:DataRecord = {}
      for (let prop in dialogForm) {
        const value = dialogForm[prop]
        if (value!=='') {
          fields[ prop ] = value
        }
      }
      if (success) success(fields)
    },

    /*
      create dynamic structure for the Dialog Form
      merge two JSON structures
    */
    updateDialogForm() {
      const { dataRecord, cleanedServiceFields } = this
      const sanitizedFields = sanitizeRecordFields(dataRecord)
      this.dialogForm = Object.assign(sanitizedFields, cleanedServiceFields)
    },

  },

  watch: {

    dataRecord(record) {
      this.updateDialogForm()
    },

  },

  created() {
    this.updateDialogForm()
  },

})
</script>
